<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommitmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommitmentRepository extends EntityRepository
{
    public function findAllApproved($em)
    {
        $query = $this->createQueryBuilder('c')
                ->join("c.step", "s")
                ->andWhere('s.approved = true')
                ->andWhere('c.approved = true')
                ->andWhere('c.spam = false')
                ->getQuery();
        
        return $query->getResult();
    }
    
    public function findAllApprovedAndFeatured($em)
    {
        $query = $this->createQueryBuilder('c')
                ->join("c.step", "s")
                ->andWhere('s.approved = true')
                ->andWhere('c.approved = true')
                ->andWhere('c.approved = true')
                ->andWhere('c.featured = true')
                ->getQuery();
        
        return $query->getResult();
    }
    
    public function findApprovedByStep($em, $step)
    {
        $query = $this->createQueryBuilder('c')
                ->join("c.step", "s")
                ->andWhere('s.approved = true')
                ->andWhere('c.approved = true')
                ->andWhere('c.spam = false')
                ->andWhere('s.id = '.$step->getId())
                ->getQuery();
        
        return $query->getResult();
    }    
}