<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedResourceRepository extends EntityRepository
{

    public function findFeaturedOnHome()
    {
        $featured = $this->findBy(array('type' => 'home'));
        
        $resources = array();
        foreach($featured as $f)
        {
            $resources[] = $f->getResource();
        }
        
        return $resources;
    }
    
    public function findFeaturedOnTakeAStep($category)
    {
        $featured = $this->findBy(array('type' => 'take a step'));
        
        $resources = array();
        foreach($featured as $f)
        {
            if($f->getResource()->getCategory() == $category) $resources[] = $f->getResource();
        }
        
        return $resources;
    }

    public function findAllFeaturedOnTakeAStep()
    {
        $featured = $this->findBy(array('type' => 'take a step'));
        
        $resources = array();
        foreach($featured as $f)
        {
            $resources[] = $f->getResource();
        }
        
        return $resources;
    }    
    
}