<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedResourceRepository extends EntityRepository
{

    public function findFeaturedOnHome()
    {
        $featured = $this->findBy(array('type' => 'home'));
        
        $organizations = array();
        foreach($featured as $f)
        {
            $organizations[] = $f->getOrganization();
        }
        
        return $organizations;
    }
    
    public function findFeaturedOnTakeAStep($category)
    {
        $featured = $this->findBy(array('type' => 'take a step'));
        
        $organizations = array();
        foreach($featured as $f)
        {
            if($f->getOrganization()->getCategory() == $category) $organizations[] = $f->getOrganization();
        }
        
        return $organizations;
    }

}