<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedStepRepository extends EntityRepository
{

    public function findFeaturedOnHome()
    {
        $featured = $this->findBy(array('type' => 'home'));
        
        $steps = array();
        foreach($featured as $f)
        {
            $steps[] = $f->getStep();
        }
        
        return $steps;
    }

}