<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeaturedResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeaturedResourceRepository extends EntityRepository
{

    public function findFeaturedOnHome()
    {
        $featured = $this->findBy(array('type' => 'home'));
        
        $resources = array();
        foreach($featured as $f)
        {
            $resources[] = $f->getResource();
        }
        
        return $resources;
    }
    
    public function findAllFeaturedOnResourceGuide()
    {
        $featured = $this->findBy(array('type' => 'resource guide'));
        
        $resources = array();
        foreach($featured as $f)
        {
            $resources[] = $f->getResource();
        }
        
        return $resources;
    }    
    
}