<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationRepository extends EntityRepository
{

    public function getCategoryAds($categories)
    {
        $orgs = array();

        if(isset($categories['all']))
        {
            foreach($this->findBy(array('organization' => true, 'approved' => true)) as $o)
            {
                $orgs[] = $o;
            }
        }
        else
        {

            foreach($categories as $c => $index)
            {
                foreach($this->findBy(array('category' => $c, 'organization' => true, 'approved' => true)) as $o)
                {
                    $orgs[] = $o;
                }
            }
        }
        return $orgs;
    }

}