<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StepSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepSubmissionRepository extends EntityRepository
{
    public function findApproved($type = null)
    {
        $query = $this->createQueryBuilder('ss')
                ->join("ss.step", "s")
                ->andWhere('s.approved = true')
                ->andWhere('ss.approved = true')
                ->andWhere('ss.spam = false');
        
        if($type) $query->andWhere('ss.type = '.$type);

        $query->orderBy('ss.datetimeSubmitted', 'DESC');
                
        return $query->getQuery()->getResult();
    }
    
    public function findApprovedAndFeatured($type = null)
    {
        $query = $this->createQueryBuilder('ss')
                ->join("ss.step", "s")
                ->andWhere('s.approved = true')
                ->andWhere('ss.approved = true')
                ->andWhere('ss.spam = false')
                ->andWhere('ss.featured = true');

        if($type) $query->andWhere('ss.type = '.$type);        

        $query->orderBy('ss.datetimeSubmitted', 'DESC');
        
        return $query->getQuery()->getResult();
    }
    
    public function findApprovedByStep($step, $type = null)
    {
        $query = $this->createQueryBuilder('ss')
                ->join("ss.step", "s")
                ->andWhere('s.approved = true')
                ->andWhere('ss.approved = true')
                ->andWhere('ss.spam = false')
                ->andWhere('s.id = '.$step->getId());
                
        if(isset($type)) $query->andWhere('ss.type = '.$type);        

        $query->orderBy('ss.datetimeSubmitted', 'DESC');
        
        return $query->getQuery()->getResult();
    }
    
}