<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends EntityRepository
{

    public function findCategoryStepTotals()
    {
        $allSteps = $this->findBy(array('approved' => true));
        $categoryTotals = array('all' => 0, 'transportation' => 0, 'food' => 0, 'waste' => 0, 'energy' => 0, 'general' => 0);
        $totalSteps = 0;
        foreach($allSteps as $step)
        {
            $categoryTotals['all'] += 1;
            $categoryTotals[$step->getCategory()] += 1;
        }

        return $categoryTotals;
    }

    public function findCategoryStepSubmissionTotals()
    {
        $allSteps = $this->findBy(array('approved' => true));
        $categoryTotals = array('all' => 0, 'transportation' => 0, 'food' => 0, 'waste' => 0, 'energy' => 0, 'general' => 0);
        $totalSteps = 0;
        foreach($allSteps as $step)
        {
            $categoryTotals['all'] += $step->getStepCount();
            $categoryTotals[$step->getCategory()] += $step->getStepCount();
        }

        return $categoryTotals;
    }

    public function findCategoryCommitmentsTotals()
    {
        $allSteps = $this->findBy(array('approved' => true));
        $categoryTotals = array('all' => 0, 'transportation' => 0, 'food' => 0, 'waste' => 0, 'energy' => 0, 'general' => 0);
        $totalSteps = 0;
        foreach($allSteps as $step)
        {
            $categoryTotals['all'] += $step->getCommitmentCount();
            $categoryTotals[$step->getCategory()] += $step->getCommitmentCount();
        }

        return $categoryTotals;
    }

    public function findByTerms($em, $terms)
    {
        $query = $this->createQueryBuilder('s');
        $query->andWhere('s.title LIKE :title');
        $query->andWhere('s.approved = 1');
        $query->setParameter('title', '%' . $terms . '%');

        return $query->getQuery()->getResult();
    }

    public function findRecentlyTaken($em)
    {
        $query = $this->createQueryBuilder('s');
        $query->leftJoin('s.stepSubmissions', 'ss');
        $query->orderBy('ss.datetimeSubmitted', 'DESC');
        $query->andWhere('s.approved = 1');
        $results = $query->getQuery()->getResult();
        
        return $results;
    }
    
    
    
    /* EVENTS ================================================================== */
    public function findAllEvents($stepSubmissionRepository, $commitmentRepository, $em)
    {
        $submissions = $stepSubmissionRepository->findAllApproved($em);
        $commitments = $commitmentRepository->findAllApproved($em);
        
        $submissionEvents = $this->turnStepsSubmissionsIntoEvents($submissions);
        $commitmentEvents = $this->turnCommitmentsIntoEvents($commitments);
                
        $events = array_merge($submissionEvents, $commitmentEvents);
        
        uasort($events, 'self::compareEvent');
        
        return $events;        
    }
    
    public function findAllFeaturedEvents($stepSubmissionRepository, $commitmentRepository, $em)
    {
        $submissions = $stepSubmissionRepository->findAllApprovedAndFeatured($em);
        $commitments = $commitmentRepository->findAllApprovedAndFeatured($em);
        
        $submissionEvents = $this->turnStepsSubmissionsIntoEvents($submissions);
        $commitmentEvents = $this->turnCommitmentsIntoEvents($commitments);
                
        $events = array_merge($submissionEvents, $commitmentEvents);
        
        uasort($events, 'self::compareEvent');
        
        return $events;        
    }
    
    public function findEventsByStep($step, $stepSubmissionRepository, $commitmentRepository, $em)
    {
        // build array of commitments and submissions for step.id
        
        // add a ":" to name if commitment/story is abbreviated
        // add quotes around text if commitment/story is abbreviated
        // abbreviate commitment/story if possible
//        $submissions = $step->getStepSubmissions();
//        $commitments = $step->getCommitments();
        $submissions = $stepSubmissionRepository->findApprovedByStep($em, $step);
        $commitments = $commitmentRepository->findApprovedByStep($em, $step);

        $submissionEvents = $this->turnStepsSubmissionsIntoEvents($submissions);
        $commitmentEvents = $this->turnCommitmentsIntoEvents($commitments);
                
        $events = array_merge($submissionEvents, $commitmentEvents);
        
        uasort($events, 'self::compareEvent');
        
        return $events;
    }
    
    public function turnStepsSubmissionsIntoEvents($submissions)
    {
        $events = array();
        
        foreach($submissions as $s)
        {
            $e = $this->turnStepSubmissionIntoEvent($s);
            $events[] = $e;
        }
        
        return $events;
    }

    public function turnStepSubmissionIntoEvent($s)
    {
        $e = array();
        if($s->storyCanBeAbbreviated())
        {
            $e['name'] = $s->getNameForDisplay();
            $e['text'] = $s->getAbbreviatedStory();
        }
        else
        {
            $e['name'] = $s->getNameForDisplay().': ';
            $e['text'] = '"'.$s->getAbbreviatedStory().'"';
        }
        $e['datetime'] = $s->getDatetimeSubmitted();                
        $e['category'] = $s->getStep()->getCategory();
        $e['stepId'] = $s->getStep()->getId();
        $e['eventId'] = $s->getId();
        $e['story'] = $s->getStory();
        $e['step'] = $s->getStep();
        $e['eventObject'] = $s;
        $e['approved'] = $s->getApproved();
        
        return $e;
    }
    
    public function turnCommitmentsIntoEvents($commitments)
    {
        $events = array();
        
        foreach($commitments as $c)
        {
            $e = $this->turnCommitmentIntoEvent($c);
            
            $events[] = $e;
        }
        
        return $events;
    }

    public function turnCommitmentIntoEvent($c)
    {
        $e = array();
        if($c->commitmentCanBeAbbreviated())
        {
            $e['name'] = $c->getNameForDisplay();
            $e['text'] = $c->getAbbreviatedCommitment();
        }
        else
        {
            $e['name'] = $c->getNameForDisplay().': ';
            $e['text'] = '"'.$c->getAbbreviatedCommitment().'"';
        }
        $e['datetime'] = $c->getDatetimeSubmitted();                
        $e['category'] = $c->getStep()->getCategory();
        $e['stepId'] = $c->getStep()->getId();
        $e['eventId'] = $c->getId();
        $e['story'] = $c->getCommitment();
        $e['step'] = $c->getStep();
        $e['eventObject'] = $c;
        $e['approved'] = $c->getApproved();

        return $e;
    }


    static function compareEvent($a, $b) {
        if ($a == $b) {
            return 0;
        }
        return ($a['datetime'] > $b['datetime']) ? -1 : 1;
    }
    
   
    
}