<?php

namespace GYGB\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StepSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepSubmissionRepository extends EntityRepository
{

  public function getRecentSteps($numberToGet, $em)
  {
    $query = $this->createQueryBuilder('ss')
            ->orderBy('ss.datetimeSubmitted', 'DESC')
            ->getQuery();
    $query->setMaxResults($numberToGet);

    return $query->getResult();
  }
  
  public function getStepList($category = null)
  {
    $query = $this->getEntityManager()
        ->createQuery('
            SELECT s, ss FROM GYGBBackBundle:StepSubmission ss
            JOIN ss.step s
       ');
    
    return $query->getResult();
  }

}