imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
    translator: { fallback: en }
            

services:
    gygb.back.admin.step:
      class: GYGB\BackBundle\Admin\StepAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Steps, label: Steps }
      arguments: [null, GYGB\BackBundle\Entity\Step, GYGBBackBundle:StepAdmin]
    gygb.back.admin.stepsubmission:
      class: GYGB\BackBundle\Admin\StepSubmissionAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Steps, label: Step Submissions }
      arguments: [null, GYGB\BackBundle\Entity\StepSubmission, GYGBBackBundle:StepSubmissionAdmin]
    gygb.back.admin.stepcommitment:
      class: GYGB\BackBundle\Admin\StepCommitmentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Steps, label: Step Commitments }
      arguments: [null, GYGB\BackBundle\Entity\Commitment, GYGBBackBundle:StepCommitmentAdmin]
    gygb.back.admin.organization:
      class: GYGB\BackBundle\Admin\OrganizationAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Resources, label: Resources }
      arguments: [null, GYGB\BackBundle\Entity\Organization, GYGBBackBundle:OrganizationAdmin]
    gygb.back.admin.featuredresource:
      class: GYGB\BackBundle\Admin\FeaturedResourceAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Featured Content, label: Featured Resources }
      arguments: [null, GYGB\BackBundle\Entity\FeaturedResource, GYGBBackBundle:FeaturedResourceAdmin]
    gygb.back.admin.featuredstep:
      class: GYGB\BackBundle\Admin\FeaturedStepAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Featured Content, label: Featured Steps }
      arguments: [null, GYGB\BackBundle\Entity\FeaturedStep, GYGBBackBundle:FeaturedStepAdmin]
    ccetc.useradmin.admin.user:
      class: CCETC\UserAdminBundle\Admin\UserAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: User Data, label: Users }
      arguments: [null, GYGB\BackBundle\Entity\User, CCETCUserAdminBundle:UserAdmin]

    errorReports:
      class: CCETC\ErrorReportBundle\Resources\config\Config
      arguments: [haggertypat@gmail.com]   

    adminSettings:
      class: Sonata\AdminBundle\Resources\config\Settings
      arguments: [Get Your GreenBack, haggertypat@gmail.com]

    userSettings:
      class: FOS\UserBundle\Resources\config\Settings
      arguments: [Get Your GreenBack, haggertypat@gmail.com, ::layout.html.twig, false, message]


# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
      adminTitle: "Get Your GreenBack"
      adminEmail: "haggertypat@gmail.com"
      
# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
       type: file
       path: %kernel.root_dir%/spool
    

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false      
    
# FOS user bundle
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: GYGB\BackBundle\Entity\User
  from_email:
    address: noreply@ccetompkins.org
    sender_name:    Get Your GreenBack
  registration:
    confirmation:
      enabled:    true
      template:   FOSUserBundle:Registration:email.txt.twig
    #form:
    #  type:               fos_user_registration
    #  handler:            fos_user.registration.form.handler.default
    #  name:               fos_user_registration_form
    #  validation_groups:  [Registration]
    