homeDefault:
  pattern:  /
  defaults: { _controller: GYGBFrontBundle:Home:home, highlightStep: false }

home:
  pattern:  /home/{highlightStep}
  defaults: { _controller: GYGBFrontBundle:Home:home, highlightStep: false }

community:
  pattern: /community
  defaults: { _controller: GYGBFrontBundle:Community:community }

communitySteps:
  pattern: /community/steps
  defaults: { _controller: GYGBFrontBundle:Community:communitySteps }

communityMap:
  pattern: /community/map
  defaults: { _controller: GYGBFrontBundle:Community:communityMap }

resources:
  pattern: /resources/{category}
  defaults: { _controller: GYGBFrontBundle:Resources:resources, category: null }
  requirements:
        category: food|waste|transportation|energy|general

# find a step -----------------------------------------------------------------
findAStep:
  pattern: /find-a-step
  defaults: { _controller: GYGBFrontBundle:FindAStep:findAStep }

takeAStep:
  pattern: /take-a-step/{id}
  defaults: { _controller: GYGBFrontBundle:TakeAStep:takeAStep, id: null, category: null }
  requirements:
        id:  \d+

shareAStep:
  pattern: /share-a-step/{id}
  defaults: { _controller: GYGBFrontBundle:ShareAStep:ShareAStep, id: null }
  
# ------------------------------------------------------------------------------

about:
  pattern: /about
  defaults: { _controller: GYGBFrontBundle:About:about }

coalition:
  pattern: /coalition
  defaults: { _controller: GYGBFrontBundle:Coalition:coalition }
  
help:
  pattern: /help
  defaults: { _controller: CCETCErrorReportBundle:ErrorReport:errorReport, includeBreadcrumb: false, flash: alert-message success, redirect: home, baseLayout: "::layout.html.twig", formRoute: help }


adminHelp:
  pattern: /help
  defaults: { _controller: CCETCErrorReportBundle:ErrorReport:errorReport, includeBreadcrumb: false, flash: alert-message success, redirect: home, baseLayout: "::layout.html.twig", formRoute: help }
  
adminHome:
  pattern: /admin/dashboard
  defaults: { _controller: SonataAdminBundle:Core:dashboard }



# admin bundle -----------------------------------------------------------------
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin  
  
    
    
# FOSUser Bundle ---------------------------------------------------------------
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password  
  