homeDefault:
  pattern:  /
  defaults: { _controller: GYGBFrontBundle:Home:home, stepTaken: false }

home:
  pattern:  /home/{stepTaken}
  defaults: { _controller: GYGBFrontBundle:Home:home, stepTaken: false }
  
steps:
  pattern: /steps/{categories}/{sort}/{savings}/{id}
  defaults: { _controller: GYGBFrontBundle:Steps:steps, categories: all, sort: popular, savings: all, id: null}

# ADMIN =====================
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin  
  
  