homeDefault:
  pattern:  /
  defaults: { _controller: GYGBFrontBundle:Home:staticHome }

home:
  pattern:  /home
  defaults: { _controller: GYGBFrontBundle:Home:staticHome }

#homeDefault:
#  pattern:  /
#  defaults: { _controller: GYGBFrontBundle:Home:home, highlightStep: false }

#home:
#  pattern:  /home/{highlightStep}
#  defaults: { _controller: GYGBFrontBundle:Home:home, highlightStep: false }

#basic:
#  pattern:  /basic
#  defaults: { _controller: GYGBFrontBundle:Home:staticHome }


organization:
  pattern:  /organization
  defaults: { _controller: GYGBFrontBundle:Organization:organization }

about:
  pattern: /about
  defaults: { _controller: GYGBFrontBundle:About:about }

coalition:
  pattern: /coalition
  defaults: { _controller: GYGBFrontBundle:Coalition:coalition }

findAStep:
  pattern: /find-a-step
  defaults: { _controller: GYGBFrontBundle:FindAStep:findAStep }

takeAStep:
  pattern: /take-a-step/{id}
  defaults: { _controller: GYGBFrontBundle:TakeAStep:takeAStep, id: null }

shareAStep:
  pattern: /share-a-step/{id}
  defaults: { _controller: GYGBFrontBundle:ShareAStep:ShareAStep, id: null }



#stepId:
#  pattern:  /steps/{id}
#  defaults: { _controller: GYGBFrontBundle:Steps:steps, categories: all, sort: recent, savings: all}
#  requirements:
#        id:  \d+
  
help:
  pattern: /help
  defaults: { _controller: CCETCErrorReportBundle:ErrorReport:errorReport, includeBreadcrumb: false, flash: message, redirect: home, baseLayout: "::layout.html.twig", formRoute: help }


adminHelp:
  pattern: /adminHelp
  defaults: { _controller: CCETCErrorReportBundle:ErrorReport:errorReport, includeBreadcrumb: true, flash: sonata_flash_success, redirect: sonata_admin_dashboard, baseLayout: SonataAdminBundle::standard_layout.html.twig, formRoute: adminHelp }
  
adminHome:
  pattern: /admin/dashboard
  defaults: { _controller: SonataAdminBundle:Core:dashboard }


# ADMIN =====================
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin  
  
    
    
# FOSUser Bundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password  
  