<?php

namespace GYGB\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends EntityRepository
{
  
  public function getNumberOfSteps($em)
  {
    $query = $em->createQuery('SELECT SUM(s.count) FROM GYGBFrontBundle:Step s');
    $count = $query->getSingleScalarResult();
    
    return $count;
  }
  
  public function getBasicSteps()
  {
    $steps = $this->findByIsBasic('1');
    
    $basicSteps = array();
    
    foreach($steps as $step)
    {
      $basicSteps[] = $step;
    }
    
    return $basicSteps;
  }
}