<?php

namespace GYGB\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StepSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepSubmissionRepository extends EntityRepository
{

  public function getRecentSteps($numberToGet, $em)
  {
    $query = $this->createQueryBuilder('ss')
            ->orderBy('ss.datetimeSubmitted', 'DESC')
            ->getQuery();
    $query->setMaxResults($numberToGet);

    return $query->getResult();
  }

}